name: Build All

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Move `private` folder
      run: mv private.sample private
    - name: Build with Gradle
      run: | 
        ./gradlew build --info --stacktrace
        ./gradlew :RMBTClient:shadowJar
        ./gradlew :RMBTMapServer:war
        ./gradlew :RMBTStatisticServer:war
        ./gradlew :RMBTQoSServer:jar
        ./gradlew :RMBTControlServer:war

    - name: Archive files
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: |
          RMBTClient/build/libs/*-all.jar
          RMBTQoSServer/build/libs/*.jar
          RMBTControlServer/build/libs/*.war
          RMBTMapServer/build/libs/*.war
          RMBTStatisticServer/build/libs/*.war
        retention-days: 365